課題3. ストップウォッチ機能が利用できるアプリを作成する
HanGuowei/FlutterStudy pull request #10
Opened 2023-05-18 00:54 UTC by cn-tre-lfp

課題3. ストップウォッチ機能が利用できるアプリを作成する

2023-05-25 03:45 UTC, MinatoIshiwata commented
@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 

こちらはレビュー開始でよろしいでしょうか？

2023-05-25 06:13 UTC, HanGuowei commented
@MinatoIshiwata  さん
レビューをよろしくお願いいたします・

2023-05-29 04:09 UTC, MinatoIshiwata commented on lib/task3/stopwatch_screen.dart
> +                        }
setState内に入れる必要は無いかと思います。

2023-05-29 04:10 UTC, MinatoIshiwata commented on lib/task3/stopwatch_screen.dart
> +                    icon: (stopwatch.isRunning)
```suggestion
                    icon: stopwatch.isRunning
```

2023-05-29 04:24 UTC, MinatoIshiwata commented on lib/task3/stopwatch_screen.dart
> +    super.dispose();
```suggestion
    _timer?.cancel();
    super.dispose();
```

2023-05-29 04:24 UTC, MinatoIshiwata requested changes
@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-05-30 01:48 UTC, MinatoIshiwata approved these changes
LGTM

@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 

suggestion changeが有った場合は取り込みを行うようにお願いいたします。

2023-05-31 08:39 UTC, MinatoIshiwata commented
@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 
マージしてください🙋

2023-06-01 03:31 UTC, merged