課題4. 本のバーコードをスキャンしてISBN値を元にAmazonの商品ページを表示する
HanGuowei/FlutterStudy pull request #11
Opened 2023-05-24 00:19 UTC by cn-tre-lfp

2023-05-25 06:14 UTC, HanGuowei commented
@MinatoIshiwata さん
課題4を開発完了しました。
レビューしてよろしくお願いいたします。

2023-05-29 06:07 UTC, MinatoIshiwata commented on lib/task4/amazon_result_screen.dart
> +    }
mapやasMapやfoldを使ってまとめられそうな気がします

2023-05-29 17:59 UTC, MinatoIshiwata reviewed
@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 
https://pub.dev/packages/mobile_scanner#:~:text=the%20visual%20editor.-,Example%2C,-%3Ckey%3E
こちらiOSの対応お願いいたします。

2023-05-30 00:47 UTC, HanGuowei commented on lib/task4/amazon_result_screen.dart
>      final sum = digits.fold(0, (previousValue, element) {
@MinatoIshiwata さん
Map　asMap  fold は全部実現してみました。
ちなみに、どちらがもっとよいですか？

2023-05-30 01:52 UTC, MinatoIshiwata commented on lib/task4/amazon_result_screen.dart
>      final sum = digits.fold(0, (previousValue, element) {
@HanGuowei 
digits.asMap().entries.foldでelement.keyがindex値なため、そちらを利用するともう少しきれいにかけるかと思います🙋

2023-05-30 01:52 UTC, MinatoIshiwata commented on lib/task4/scanner_screen.dart
> +  List<Barcode> scanResultListForBarcode = [];
こちら `_` つけたほうが良いと思います

2023-05-30 01:54 UTC, MinatoIshiwata requested changes
@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-05-31 13:14 UTC, MinatoIshiwata commented on lib/task4/amazon_result_screen.dart
> +        );
いいかんじです🙋

2023-05-31 13:42 UTC, MinatoIshiwata approved these changes
LGTM👍

2023-06-01 06:02 UTC, merged