課題5. GitHub APIを利用して、指定したリポジトリの情報を取得し、リスト形式で表示するアプリを作成する
HanGuowei/FlutterStudy pull request #12
Opened 2023-05-30 08:36 UTC by cn-tre-lfp

2023-06-01 06:05 UTC, HanGuowei commented
@MinatoIshiwata さん

課題５を開発完了しました。
レビューしてよろしくお願いいたします。

2023-06-04 06:41 UTC, MinatoIshiwata commented on lib/task5/repository_screen.dart
> +            tabs: [Tab(text: 'Readme'), Tab(text: 'Issues')],
`Tab(text: 'Issues')` の後に `,` を追加してフォーマットしてみてください

2023-06-04 06:41 UTC, MinatoIshiwata commented on lib/task5/repository_screen.dart
> +          children: [_readmeBuild(), _issuesBuild()],
こちらも末尾に, を追加してフォーマットしてみてください

2023-06-04 06:45 UTC, MinatoIshiwata commented on lib/task5/repository_screen.dart
> +          final issue = _issues[index] as Map;
freezedやjson_serializableなどでORMしてから利用しましょう🙋

2023-06-04 06:51 UTC, MinatoIshiwata commented on lib/task5/search_screen.dart
> +  final _textEditingController =
こちらdispose必要です🙋

2023-06-04 07:24 UTC, MinatoIshiwata requested changes
何点かコメントいたしました。
https://medium.com/flutter-jp/analysis-b8dbb19d3978
こちらを利用して静的解析を追加、警告・エラーが出ないように対応をお願いいたします。

2023-06-08 01:46 UTC, HanGuowei commented
> 何点かコメントいたしました。 https://medium.com/flutter-jp/analysis-b8dbb19d3978 こちらを利用して静的解析を追加、警告・エラーが出ないように対応をお願いいたします。

対応済みでした。ご確認をお願いします。

2023-06-08 04:15 UTC, MinatoIshiwata commented on lib/task5/model/repository_issue.dart
> +  @JsonSerializable(fieldRename: FieldRename.snake)
build.yamlで指定すると良いと思います🙋

2023-06-08 04:17 UTC, MinatoIshiwata commented on lib/task5/model/repository_issue.freezed.dart
https://zenn.dev/mamushi/articles/hide_generated_file_diff

2023-06-08 04:19 UTC, MinatoIshiwata commented on lib/task5/repository_screen.dart
> +  final ScrollController _issuesScrollController = ScrollController();
disposeを忘れずに追加ください🙋

2023-06-08 04:28 UTC, MinatoIshiwata requested changes
@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 
複数点コメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-06-12 00:32 UTC, HanGuowei commented
@MinatoIshiwata さん
対応を行いました。
よろしくお願いいたします

2023-06-12 13:40 UTC, MinatoIshiwata requested changes
iOSの表示に無理があります、タップできません。
![Simulator Screen Shot - iPhone 14 Pro - 2023-06-12 at 21 57 10](https://github.com/HanGuowei/FlutterStudy/assets/44658075/23cae4b5-c987-45c1-a157-c6aa76aef0b1)

通信後エラーが出るので解消ください。

以上、ご確認のほどよろしくお願いいたします。

2023-06-16 00:37 UTC, MinatoIshiwata commented
@cn-tre-lfp 
@HanGuowei 
@trechina-zhangzhen 
こちら状況はいかがでしょうか？

2023-06-21 14:34 UTC, MinatoIshiwata approved these changes
LGTM

2023-06-26 00:59 UTC, merged