課題6-1. ニュースAPIを利用して、最新のニュースを表示するアプリを作成する
HanGuowei/FlutterStudy pull request #14
Opened 2023-06-08 08:22 UTC by cn-tre-lfp

## 対応するIssue

#9 

## きのう

- リフレッシュインジケータを使用して実現されたプルダウン更新
- キーワード検索
-  記事をクリックすると、対象のウェブページがWebViewで表示され、右上隅でお気に入りを選択できます
- ホームタブの2番目のメニューアイテムにはすべてのお気に入りを表示するオプションがあります

## 画面

![image](https://github.com/HanGuowei/FlutterStudy/assets/110440011/57fe6716-883f-44f0-81f7-7c9eb248e09f)
![image](https://github.com/HanGuowei/FlutterStudy/assets/110440011/e8a419ed-4c60-4ec7-b1fc-574732354bcc)
![image](https://github.com/HanGuowei/FlutterStudy/assets/110440011/00666282-c125-4bcf-8213-0739eee07fe9)

2023-06-08 23:47 UTC, utamori commented on lib/task6/entity/article_bean.dart
> +class ArticlesBean {
@immutable　にしてください

2023-06-08 23:47 UTC, utamori commented on lib/task6/entity/news_bean.dart
> +class NewsBean {
@immutableにする

2023-06-08 23:47 UTC, utamori commented on lib/task6/entity/source_bean.dart
> +  SourceBean({required this.id, required this.name});
@immutableにする

2023-06-08 23:48 UTC, utamori commented on lib/task6/entity/source_bean.dart
> +  SourceBean({required this.id, required this.name});
Javaじゃないので、Beanと命名する意味ないです

2023-06-08 23:50 UTC, utamori commented on lib/task6/news_screen.dart
> +  }
Widgetを返す関数は、パフォーマンスが悪いのでbad practiceです。　別Widgetクラスとして定義してください

2023-06-08 23:50 UTC, utamori commented on lib/task6/news_screen.dart
> +    super.initState();
removeListenerも忘れずに

2023-06-08 23:52 UTC, utamori commented on lib/task6/news_screen.dart
> +          }
ifのネストは避けましょう
early returnか、 switch文を使いましょう



```

2023-06-08 23:55 UTC, utamori commented on lib/task6/news_screen.dart
> +          }
```dart
  if (index < _articles.length) {
    return Article(
      onTap: () {
        _navigationToDetail(_articles[index]);
      },
      articlesBean: _articles[index],
    );
  }
  if (_isMaxResult) {
    return const Text('No more articles');
  }
  if (_isMoreLoading) {
    return null;
  }
  return const Center(
    child: Padding(
      padding: EdgeInsets.all(5),
      child: CircularProgressIndicator(),
    ),
  );
```

2023-06-08 23:55 UTC, utamori requested changes
レビューしました

2023-06-09 00:21 UTC, HanGuowei commented
> レビューしました
ありがとうございます。確認します。

2023-06-12 00:33 UTC, HanGuowei commented
@utamori 
対応を行いました。
よろしくお願いいたします

2023-06-21 14:49 UTC, MinatoIshiwata requested changes
@cn-tre-lfp 
@HanGuowei 
@wwalkingg 
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-06-26 01:38 UTC, cn-tre-lfp commented on lib/task6/api/news_api.dart
> +    ..options.headers = {'X-Api-Key': '0b99e4557cbd4f3f85e11cddde8a38a9'};
お疲れ様です。敏感な情報を.envファイルに移動しました。'NEWS_API_KEY='の後に有効なキーを入力してください。以前のキーはニュースAPIから削除しました。必要であれば、他のプラットフォームからキーをお送りいたしますので、お知らせください。

2023-06-26 01:38 UTC, cn-tre-lfp commented on lib/task6/favorite_store_model.dart
> +class FavoriteStoreModel extends ChangeNotifier {
「riverpod」と「riverpod generate」を使用して、Providerの一部を書き直しました。

2023-06-26 01:54 UTC, cn-tre-lfp commented on lib/task6/api/news_api.dart
> +    ..options.headers = {'X-Api-Key': '0b99e4557cbd4f3f85e11cddde8a38a9'};
無料のAPIキーはキーの変更をサポートしていないようです。

2023-06-27 06:50 UTC, MinatoIshiwata commented
@cn-tre-lfp 
本タスクはStatefulWidgetの機能のみで実装をお願いしたいです。
今一度見直しをお願いいたします。
riverpodは課題7で適用してください。
ご確認のほどよろしくお願いいたします。

2023-06-27 08:23 UTC, cn-tre-lfp commented
@MinatoIshiwata 
すべてのriverpod依存関係を削除し、以前riverpodを使用していたコンテンツを書き直しました。現在、ウィジェットの適切なライフサイクルでお気に入りリストをロードするように修正しました。ご確認よろしくお願いいたします。

2023-06-27 08:27 UTC, cn-tre-lfp reviewed
remove riverpod

2025-07-25 03:50 UTC, closed without merging