課題2. テキストフィールドに入力された文字列を表示するシンプルなToDoリストアプリを作成する
HanGuowei/FlutterStudy pull request #22
Opened 2023-08-18 03:12 UTC by superSong-hello

# このプルリクの目的
テキストフィールドに入力された文字列を表示するシンプルなToDoリストアプリを作成する

## 具体的な作業内容（変更内容も含む）
- [x] add todo list

2023-08-18 04:41 UTC, MinatoIshiwata commented on lib/task2/todo_list_page.dart
> +    return null;
パターンマッチで対応してみましょう。

2023-08-18 04:42 UTC, MinatoIshiwata commented on lib/task2/todo_list_page.dart
> +                _formKey.currentState!.save();
フォースアンラップしないようにお願いいたします。

2023-08-18 04:43 UTC, MinatoIshiwata commented on lib/task2/todo_list_page.dart
> +                    _dataArray[index] = value!;
フォースアンラップしないようにお願いいたします。

2023-08-18 04:46 UTC, MinatoIshiwata commented on lib/task2/todo_list_page.dart
> +      body: _dataArray.isNotEmpty ? ListView.builder(
SafeAreaで囲って欲しいです。

2023-08-18 04:46 UTC, MinatoIshiwata reviewed
何点かコメントいたしました。

2023-08-18 04:47 UTC, MinatoIshiwata requested changes
対応をお願いいたします。

2023-08-18 06:32 UTC, superSong-hello commented on lib/task2/todo_list_page.dart
> +                _formKey.currentState!.save();
👌🏻

2023-08-18 07:51 UTC, superSong-hello commented on lib/task2/todo_list_page.dart
> +      body: _dataArray.isNotEmpty ? ListView.builder(
こんにちは、対応する質問です

2023-08-21 00:39 UTC, superSong-hello commented
> 対応をお願いいたします。

こんにちは、終わりました

2023-08-21 02:20 UTC, MinatoIshiwata commented on lib/task2/todo_list_page.dart
> +  const TodoCell({
```suggestion
class _TodoCell extends StatelessWidget {
  const _TodoCell({
```

2023-08-21 02:21 UTC, MinatoIshiwata commented on lib/task2/todo_list_page.dart
> +            return TodoCell(
```suggestion
            return _TodoCell(
```

2023-08-21 02:22 UTC, MinatoIshiwata approved these changes
suggest commentを取り込んでください
LGTM

2023-08-22 00:27 UTC, merged