課題6-1. ニュースAPIを利用して、最新のニュースを表示するアプリを作成する
HanGuowei/FlutterStudy pull request #26
Opened 2023-08-25 01:38 UTC by superSong-hello

# このプルリクの目的
ニュースAPIを利用して、最新のニュースを表示するアプリを作成する

## 具体的な作業内容（変更内容も含む）
- [x] add news module

2023-08-28 05:17 UTC, MinatoIshiwata commented on analysis_options.yaml
> +    - lib/**/*.dart
これはすべての.dartの静的解析をしないので追加しないでください。

2023-08-28 05:20 UTC, MinatoIshiwata commented on lib/task5/utils/dio_util.dart
> +    options.headers['X-Api-Key'] = 'e20a599bdafc41f4a81675ec1068e9b6';
apikeyをそのまま載せないでください。
また、こちらのコミットから除外してください。
https://codewithandrea.com/articles/flutter-api-keys-dart-define-env-files/

2023-08-28 05:23 UTC, MinatoIshiwata commented on lib/task6/article_manager.dart
> +      favoritesArticleArray.any((element) => element.url == info.url);
urlはおそらくuniqueではない可能性があります。
SourceInfoのidなどをご利用ください。

2023-08-28 05:23 UTC, MinatoIshiwata commented on lib/task6/article_manager.dart
> +        ..removeWhere((element) => element.url == info.url);
urlはおそらくuniqueではない可能性があります。
SourceInfoのidなどをご利用ください。

2023-08-28 05:23 UTC, MinatoIshiwata commented on lib/task6/favorites_list_page.dart
> +          : _emptyWidget(),
ローカルのクラスで良いので、クラス化してください。

2023-08-28 05:26 UTC, MinatoIshiwata commented on lib/task6/news_list_page.dart
> +  }
ローカルクラスのWidgetにしてください。

2023-08-28 05:26 UTC, MinatoIshiwata approved these changes
@superSong-hello 
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-08-28 06:51 UTC, superSong-hello commented on lib/task6/article_manager.dart
> +        ..removeWhere((element) => element.url == info.url);
![截屏2023-08-28 14 48 09](https://github.com/HanGuowei/FlutterStudy/assets/66933703/0407675b-bf36-46fc-ad06-5680b298422e)

こんにちは。現在のニュース データは少し不規則です。ID を一意の識別子として使用することはできず、null になる可能性があります。コレクションの効果をテストするために、URL が一時的に使用されます。

2023-08-28 07:15 UTC, superSong-hello commented
> @superSong-hello 何点かコメントいたしました。 ご確認のほどよろしくお願いいたします。

こんにちは、問題は確認されており、疑問点はすべて解決されました

2023-08-29 05:12 UTC, MinatoIshiwata commented on lib/task6/article_manager.dart
> +        ..removeWhere((element) => element.url == info.url);
そうしましたら、[こちら](https://api.dart.dev/stable/2.13.4/dart-core/Object/operator_equals.html)を利用して一致するか否かを判定できるようにしてurlのみでなく複数の値を利用してユニークであることをチェックしてください。

2023-08-29 05:13 UTC, MinatoIshiwata requested changes
Flutter Analyzeが通る状態でレビューの依頼をお願いいたします。

2023-08-29 06:52 UTC, superSong-hello commented on lib/task6/article_manager.dart
> +        ..removeWhere((element) => element.url == info.url);
This is just a test to verify the function, the real development will definitely have a unique identifier, use the unique identifier to judge

2023-08-29 06:58 UTC, superSong-hello commented
> Flutter Analyzeが通る状態でレビューの依頼をお願いいたします。

Hello, please review again

2023-08-29 19:29 UTC, MinatoIshiwata approved these changes

2023-08-30 00:02 UTC, merged