課題7. ニュースAPIを利用して、最新のニュースを表示するアプリを作成する
HanGuowei/FlutterStudy pull request #27
Opened 2023-08-30 03:15 UTC by superSong-hello

# このプルリクの目的
課題7. ニュースAPIを利用して、最新のニュースを表示するアプリを作成する

## 具体的な作業内容（変更内容も含む）
- [x] add riverpod manager state

2023-08-30 03:25 UTC, MinatoIshiwata commented on lib/task7/controller/article_list_notifier.dart
https://pub.dev/packages/riverpod_generator
を利用してください。Pacerではこちらを利用しています。

StateNotifierは非推奨です。Notifierを利用してください。

2023-08-30 04:40 UTC, superSong-hello commented on lib/task7/controller/article_list_notifier.dart
> https://pub.dev/packages/riverpod_generator を利用してください。Pacerではこちらを利用しています。
> 
> StateNotifierは非推奨です。Notifierを利用してください。

Hello, I have a question. A large-scale project uses too much automatic code generation. How to deal with the high post-compilation cost?

2023-08-30 05:13 UTC, MinatoIshiwata commented on lib/task7/controller/article_list_notifier.dart
@superSong-hello 
コード生成が不可欠、用意されているプロバイダの種類が少ない意外にそこまでデメリットはないかと思います。
`flutter pub run build_runner watch` 生成に関してはこちらのコマンドを実行しておくことでデメリット回避できるかと思います。
メリットのほうが大きいから利用していると考えられます。
https://codewithandrea.com/articles/flutter-riverpod-generator/#riverpod-generator-tradeoffs:~:text=with%20Timeout.-,Riverpod%20Generator%3A%20Tradeoffs,-Now%20that%20we%27ve

2023-08-30 06:31 UTC, superSong-hello commented on lib/task7/controller/article_list_notifier.dart
Hello, please review again

2023-08-30 07:09 UTC, MinatoIshiwata commented on lib/task7/controller/article_notifier.dart
> +      ];
whereでまとめられるかと思います、ご確認のほどよろしくお願いいたします。

2023-08-30 07:12 UTC, MinatoIshiwata commented on lib/task7/news_detail_page.dart
> +    _controller.loadRequest(
''をparseするとクラッシュするかと思いますので、事前にnullチェックしてください。

2023-08-30 07:23 UTC, MinatoIshiwata commented on lib/task7/news_list_page.dart
> +  final _searchController = TextEditingController(text: '');
_searchControllerをdisposeする必要があるかと思います。

2023-08-30 07:24 UTC, MinatoIshiwata requested changes
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-08-30 08:16 UTC, superSong-hello commented
> 何点かコメントいたしました。 ご確認のほどよろしくお願いいたします。

Hello, the code has been modified, please review again

2023-08-31 03:05 UTC, MinatoIshiwata commented on lib/task7/api/news_api.dart
> +    }
exeption時はnull返したほうが良さそうですか？

2023-08-31 03:16 UTC, MinatoIshiwata commented on lib/task7/news_detail_page.dart
> +    _controller.loadRequest(
tryParseも利用しましょう！

2023-08-31 03:17 UTC, MinatoIshiwata reviewed
1点だけご確認ほどよろしくお願いします。

2023-08-31 03:29 UTC, superSong-hello commented on lib/task7/api/news_api.dart
> +    }
Returning null is to handle pull-down refresh or pull-up loading. During normal development, toast will be played at the same time.

2023-08-31 04:54 UTC, MinatoIshiwata commented on lib/task7/api/news_api.dart
> +    }
OK

2023-08-31 04:55 UTC, MinatoIshiwata approved these changes

2023-08-31 05:03 UTC, merged